export interface ResponseFieldDef {
  readonly name: string;
  readonly description: string;
}

// === Shared field groups ===

const INDEX_COMMON_FIELDS: readonly ResponseFieldDef[] = [
  { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
  { name: "IDX_CLSS", description: "계열구분" },
  { name: "IDX_NM", description: "지수명" },
  { name: "CLSPRC_IDX", description: "종가" },
  { name: "CMPPREVDD_IDX", description: "전일대비" },
  { name: "FLUC_RT", description: "등락률(%)" },
  { name: "OPNPRC_IDX", description: "시가" },
  { name: "HGPRC_IDX", description: "고가" },
  { name: "LWPRC_IDX", description: "저가" },
  { name: "ACC_TRDVOL", description: "거래량" },
  { name: "ACC_TRDVAL", description: "거래대금" },
  { name: "MKTCAP", description: "상장시가총액" },
];

const STOCK_DAILY_FIELDS: readonly ResponseFieldDef[] = [
  { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
  { name: "ISU_CD", description: "종목코드" },
  { name: "ISU_NM", description: "종목명" },
  { name: "MKT_NM", description: "시장구분" },
  { name: "SECT_TP_NM", description: "소속부" },
  { name: "TDD_CLSPRC", description: "종가" },
  { name: "CMPPREVDD_PRC", description: "전일대비" },
  { name: "FLUC_RT", description: "등락률(%)" },
  { name: "TDD_OPNPRC", description: "시가" },
  { name: "TDD_HGPRC", description: "고가" },
  { name: "TDD_LWPRC", description: "저가" },
  { name: "ACC_TRDVOL", description: "거래량" },
  { name: "ACC_TRDVAL", description: "거래대금" },
  { name: "MKTCAP", description: "시가총액" },
  { name: "LIST_SHRS", description: "상장주식수" },
];

const STOCK_BASE_INFO_FIELDS: readonly ResponseFieldDef[] = [
  { name: "ISU_CD", description: "표준코드" },
  { name: "ISU_SRT_CD", description: "단축코드" },
  { name: "ISU_NM", description: "한글종목명" },
  { name: "ISU_ABBRV", description: "한글종목약명" },
  { name: "ISU_ENG_NM", description: "영문종목명" },
  { name: "LIST_DD", description: "상장일" },
  { name: "MKT_TP_NM", description: "시장구분" },
  { name: "SECUGRP_NM", description: "증권구분" },
  { name: "SECT_TP_NM", description: "소속부" },
  { name: "KIND_STKCERT_TP_NM", description: "주식종류" },
  { name: "PARVAL", description: "액면가" },
  { name: "LIST_SHRS", description: "상장주식수" },
];

const BOND_DAILY_FIELDS: readonly ResponseFieldDef[] = [
  { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
  { name: "MKT_NM", description: "시장구분" },
  { name: "ISU_CD", description: "종목코드" },
  { name: "ISU_NM", description: "종목명" },
  { name: "CLSPRC", description: "종가" },
  { name: "CMPPREVDD_PRC", description: "전일대비" },
  { name: "CLSPRC_YD", description: "종가수익률" },
  { name: "OPNPRC", description: "시가" },
  { name: "OPNPRC_YD", description: "시가수익률" },
  { name: "HGPRC", description: "고가" },
  { name: "HGPRC_YD", description: "고가수익률" },
  { name: "LWPRC", description: "저가" },
  { name: "LWPRC_YD", description: "저가수익률" },
  { name: "ACC_TRDVOL", description: "거래량" },
  { name: "ACC_TRDVAL", description: "거래대금" },
];

const FUTURES_FIELDS: readonly ResponseFieldDef[] = [
  { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
  { name: "PROD_NM", description: "상품명" },
  { name: "MKT_NM", description: "시장구분" },
  { name: "ISU_CD", description: "종목코드" },
  { name: "ISU_NM", description: "종목명" },
  { name: "TDD_CLSPRC", description: "종가" },
  { name: "CMPPREVDD_PRC", description: "전일대비" },
  { name: "TDD_OPNPRC", description: "시가" },
  { name: "TDD_HGPRC", description: "고가" },
  { name: "TDD_LWPRC", description: "저가" },
  { name: "SPOT_PRC", description: "현물가" },
  { name: "SETL_PRC", description: "정산가" },
  { name: "ACC_TRDVOL", description: "거래량" },
  { name: "ACC_TRDVAL", description: "거래대금" },
  { name: "ACC_OPNINT_QTY", description: "미결제약정수량" },
];

const OPTIONS_FIELDS: readonly ResponseFieldDef[] = [
  { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
  { name: "PROD_NM", description: "상품명" },
  { name: "RGHT_TP_NM", description: "권리유형 (콜/풋)" },
  { name: "ISU_CD", description: "종목코드" },
  { name: "ISU_NM", description: "종목명" },
  { name: "TDD_CLSPRC", description: "종가" },
  { name: "CMPPREVDD_PRC", description: "전일대비" },
  { name: "TDD_OPNPRC", description: "시가" },
  { name: "TDD_HGPRC", description: "고가" },
  { name: "TDD_LWPRC", description: "저가" },
  { name: "IMP_VOLT", description: "내재변동성" },
  { name: "NXTDD_BAS_PRC", description: "익일기준가" },
  { name: "ACC_TRDVOL", description: "거래량" },
  { name: "ACC_TRDVAL", description: "거래대금" },
  { name: "ACC_OPNINT_QTY", description: "미결제약정수량" },
];

// === Per-endpoint response fields ===

export const RESPONSE_FIELDS: Record<string, readonly ResponseFieldDef[]> = {
  // Index
  "/svc/apis/idx/krx_dd_trd": INDEX_COMMON_FIELDS,
  "/svc/apis/idx/kospi_dd_trd": INDEX_COMMON_FIELDS,
  "/svc/apis/idx/kosdaq_dd_trd": INDEX_COMMON_FIELDS,
  "/svc/apis/idx/bon_dd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "BND_IDX_GRP_NM", description: "채권지수그룹명" },
    { name: "TOT_EARNG_IDX", description: "총수익지수" },
    { name: "TOT_EARNG_IDX_CMPPREVDD", description: "총수익지수 전일대비" },
    { name: "NETPRC_IDX", description: "순가격지수" },
    { name: "NETPRC_IDX_CMPPREVDD", description: "순가격지수 전일대비" },
    { name: "ZERO_REINVST_IDX", description: "제로재투자지수" },
    {
      name: "ZERO_REINVST_IDX_CMPPREVDD",
      description: "제로재투자지수 전일대비",
    },
    { name: "CALL_REINVST_IDX", description: "콜재투자지수" },
    {
      name: "CALL_REINVST_IDX_CMPPREVDD",
      description: "콜재투자지수 전일대비",
    },
    { name: "MKT_PRC_IDX", description: "시가지수" },
    { name: "MKT_PRC_IDX_CMPPREVDD", description: "시가지수 전일대비" },
    { name: "AVG_DURATION", description: "평균듀레이션" },
    { name: "AVG_CONVEXITY_PRC", description: "평균컨벡시티" },
    { name: "BND_IDX_AVG_YD", description: "채권지수 평균수익률" },
  ],
  "/svc/apis/idx/drvprod_dd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "IDX_CLSS", description: "계열구분" },
    { name: "IDX_NM", description: "지수명" },
    { name: "CLSPRC_IDX", description: "종가" },
    { name: "CMPPREVDD_IDX", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "OPNPRC_IDX", description: "시가" },
    { name: "HGPRC_IDX", description: "고가" },
    { name: "LWPRC_IDX", description: "저가" },
  ],

  // Stock daily
  "/svc/apis/sto/stk_bydd_trd": STOCK_DAILY_FIELDS,
  "/svc/apis/sto/ksq_bydd_trd": STOCK_DAILY_FIELDS,
  "/svc/apis/sto/knx_bydd_trd": STOCK_DAILY_FIELDS,
  "/svc/apis/sto/sw_bydd_trd": [
    ...STOCK_DAILY_FIELDS,
    { name: "EXER_PRC", description: "행사가격" },
    { name: "EXST_STRT_DD", description: "행사시작일" },
    { name: "EXST_END_DD", description: "행사종료일" },
    { name: "TARSTK_ISU_SRT_CD", description: "대상주식 단축코드" },
    { name: "TARSTK_ISU_NM", description: "대상주식 종목명" },
    { name: "TARSTK_ISU_PRSNT_PRC", description: "대상주식 현재가" },
  ],
  "/svc/apis/sto/sr_bydd_trd": STOCK_DAILY_FIELDS,

  // Stock base info
  "/svc/apis/sto/stk_isu_base_info": STOCK_BASE_INFO_FIELDS,
  "/svc/apis/sto/ksq_isu_base_info": STOCK_BASE_INFO_FIELDS,
  "/svc/apis/sto/knx_isu_base_info": STOCK_BASE_INFO_FIELDS,

  // ETP
  "/svc/apis/etp/etf_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "NAV", description: "순자산가치(NAV)" },
    { name: "TDD_OPNPRC", description: "시가" },
    { name: "TDD_HGPRC", description: "고가" },
    { name: "TDD_LWPRC", description: "저가" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
    { name: "MKTCAP", description: "시가총액" },
    { name: "INVSTASST_NETASST_TOTAMT", description: "순자산총액" },
    { name: "LIST_SHRS", description: "상장주식수" },
    { name: "IDX_IND_NM", description: "기초지수명" },
    { name: "OBJ_STKPRC_IDX", description: "기초지수종가" },
    { name: "CMPPREVDD_IDX", description: "기초지수 전일대비" },
    { name: "FLUC_RT_IDX", description: "기초지수 등락률(%)" },
  ],
  "/svc/apis/etp/etn_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "PER1SECU_INDIC_VAL", description: "1증권당 지표가치" },
    { name: "TDD_OPNPRC", description: "시가" },
    { name: "TDD_HGPRC", description: "고가" },
    { name: "TDD_LWPRC", description: "저가" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
    { name: "MKTCAP", description: "시가총액" },
    { name: "INDIC_VAL_AMT", description: "지표가치총액" },
    { name: "LIST_SHRS", description: "상장주식수" },
    { name: "IDX_IND_NM", description: "기초지수명" },
    { name: "OBJ_STKPRC_IDX", description: "기초지수종가" },
    { name: "CMPPREVDD_IDX", description: "기초지수 전일대비" },
    { name: "FLUC_RT_IDX", description: "기초지수 등락률(%)" },
  ],
  "/svc/apis/etp/elw_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "TDD_OPNPRC", description: "시가" },
    { name: "TDD_HGPRC", description: "고가" },
    { name: "TDD_LWPRC", description: "저가" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
    { name: "MKTCAP", description: "시가총액" },
    { name: "LIST_SHRS", description: "상장주식수" },
    { name: "ULY_NM", description: "기초자산명" },
    { name: "ULY_PRC", description: "기초자산가격" },
    { name: "CMPPREVDD_PRC_ULY", description: "기초자산 전일대비" },
    { name: "FLUC_RT_ULY", description: "기초자산 등락률(%)" },
  ],

  // Bond
  "/svc/apis/bon/kts_bydd_trd": [
    ...BOND_DAILY_FIELDS.slice(0, 4),
    { name: "BND_EXP_TP_NM", description: "채권만기구분" },
    { name: "GOVBND_ISU_TP_NM", description: "국채발행유형" },
    ...BOND_DAILY_FIELDS.slice(4),
  ],
  "/svc/apis/bon/bnd_bydd_trd": BOND_DAILY_FIELDS,
  "/svc/apis/bon/smb_bydd_trd": BOND_DAILY_FIELDS,

  // Derivative - Futures
  "/svc/apis/drv/fut_bydd_trd": FUTURES_FIELDS,
  "/svc/apis/drv/eqsfu_stk_bydd_trd": FUTURES_FIELDS,
  "/svc/apis/drv/eqkfu_ksq_bydd_trd": FUTURES_FIELDS,

  // Derivative - Options
  "/svc/apis/drv/opt_bydd_trd": OPTIONS_FIELDS,
  "/svc/apis/drv/eqsop_bydd_trd": OPTIONS_FIELDS,
  "/svc/apis/drv/eqkop_bydd_trd": OPTIONS_FIELDS,

  // Commodity
  "/svc/apis/gen/oil_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "OIL_NM", description: "유종명" },
    { name: "WT_AVG_PRC", description: "가중평균가격" },
    { name: "WT_DIS_AVG_PRC", description: "가중할인평균가격" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
  ],
  "/svc/apis/gen/gold_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "TDD_OPNPRC", description: "시가" },
    { name: "TDD_HGPRC", description: "고가" },
    { name: "TDD_LWPRC", description: "저가" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
  ],
  "/svc/apis/gen/ets_bydd_trd": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "TDD_OPNPRC", description: "시가" },
    { name: "TDD_HGPRC", description: "고가" },
    { name: "TDD_LWPRC", description: "저가" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
  ],

  // ESG
  "/svc/apis/esg/sri_bond_info": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISUR_NM", description: "발행기관명" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "SRI_BND_TP_NM", description: "SRI채권유형" },
    { name: "ISU_NM", description: "종목명" },
    { name: "LIST_DD", description: "상장일" },
    { name: "ISU_DD", description: "발행일" },
    { name: "REDMPT_DD", description: "상환일" },
    { name: "ISU_RT", description: "발행이율" },
    { name: "ISU_AMT", description: "발행금액" },
    { name: "LIST_AMT", description: "상장금액" },
    { name: "BND_TP_NM", description: "채권유형" },
  ],
  "/svc/apis/esg/esg_etp_info": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "ISU_CD", description: "종목코드" },
    { name: "ISU_NM", description: "종목명" },
    { name: "TDD_CLSPRC", description: "종가" },
    { name: "CMPPREVDD_PRC", description: "전일대비" },
    { name: "FLUC_RT", description: "등락률(%)" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
  ],
  "/svc/apis/esg/esg_index_info": [
    { name: "BAS_DD", description: "기준일자 (YYYYMMDD)" },
    { name: "IDX_NM", description: "지수명" },
    { name: "CLSPRC_IDX", description: "종가" },
    { name: "PRV_DD_CMPR", description: "전일대비" },
    { name: "UPDN_RATE", description: "등락률(%)" },
    { name: "TRD_ISU_CNT", description: "거래종목수" },
    { name: "ACC_TRDVOL", description: "거래량" },
    { name: "ACC_TRDVAL", description: "거래대금" },
  ],
};
